version: '3.9'

services:
  rabbitmq:
    image: rabbitmq
    restart: always

  # redis:
  #   image: redis
  #   restart: always

  backend:
    restart: always
    build: 
      context: ./backend
    ports:
      ["8000:8000"]
    command: ["python3", "./src/manage.py", "runserver", "0.0.0.0:8000"]

  worker:
    restart: always
    build:
      context: ./backend
    command: ['celery', '--workdir=./src', '-A', 'proj', 'worker']