version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "testpassword"

  redis:
    image: redis
    restart: always

  backend:
    restart: always
    build: 
      context: ./backend
    ports:
      ["8000:8000"]
    command: ["python3", "./src/manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db

  worker:
    restart: always
    build:
      context: ./backend
    command: ['celery', '--workdir=./src', '-A', 'proj', 'worker']

  celery-beats:
    restart: always
    build:
      context: ./backend
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    command: ['celery', '--workdir=./src', '-A', 'proj', 'beat', '-l', 'INFO', '--scheduler', 'django_celery_beat.schedulers:DatabaseScheduler']