# Generated by Django 4.1.4 on 2022-12-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('rouble_cost', models.IntegerField()),
            ],
        ),
    ]
